// Virtual Worlds – curated seed data for the map
import type { WorldMarker } from './worldTypes';

export const SEED_WORLDS: WorldMarker[] = [
  // ── Enchanted Forests (social / roleplay) ──────────────────────────────
  {
    id: 'second-life',
    name: 'Second Life',
    lore: 'Where souls seek another existence beyond mortal flesh — the oldest of the Great Kingdoms, built upon millions of whispered wishes.',
    description: 'The original metaverse. A vast 3D social world where users build, trade, and live alternate lives.',
    url: 'https://secondlife.com',
    thumbnail: 'https://images.unsplash.com/photo-1518050346340-aa2ec3bb424b?w=400&q=80',
    biome: 'enchanted-forest',
    tags: ['Social', 'Roleplay', 'Free', 'Desktop'],
    coordinates: [1520, 480],
    visitors: 824_000,
    rating: 4.1,
  },
  {
    id: 'vrchat',
    name: 'VRChat',
    lore: 'The Grand Agora of Avatars — a realm where any form may be worn and any world can be entered through crystalline gates.',
    description: 'Social VR platform with user-generated worlds and expressive avatar customization.',
    url: 'https://vrchat.com',
    thumbnail: 'https://images.unsplash.com/photo-1626379616243-44dc20e77de0?w=400&q=80',
    biome: 'crystal-spires',
    tags: ['VR', 'Social', 'Free', 'Multiplayer'],
    coordinates: [820, 960],
    visitors: 5_200_000,
    rating: 4.7,
  },
  // ── Mountain Forges (creative sandboxes) ───────────────────────────────
  {
    id: 'minecraft',
    name: 'Minecraft',
    lore: 'The Forge Eternal — where from raw stone and timber, entire civilisations rise at the will of the maker.',
    description: 'The legendary block-building sandbox beloved by hundreds of millions across the globe.',
    url: 'https://minecraft.net',
    thumbnail: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400&q=80',
    biome: 'mountain-forge',
    tags: ['Sandbox', 'Creative', 'Multiplayer', 'Paid'],
    coordinates: [2100, 700],
    visitors: 175_000_000,
    rating: 4.9,
  },
  {
    id: 'roblox',
    name: 'Roblox',
    lore: 'The Infinite Spire of Games — a tower that contains ten thousand worlds, each built by young artificers who dare to dream.',
    description: 'Massively popular platform letting users create and play in millions of user-made games.',
    url: 'https://roblox.com',
    thumbnail: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80',
    biome: 'mountain-forge',
    tags: ['Sandbox', 'Free', 'Multiplayer', 'Mobile'],
    coordinates: [2350, 900],
    visitors: 214_000_000,
    rating: 4.3,
  },
  // ── Crystal Spires (VR / metaverse) ───────────────────────────────────
  {
    id: 'decentraland',
    name: 'Decentraland',
    lore: 'The Crystal Sovereignty — an autonomous realm where land is forever enshrined in the Blockchain Codex, owned by its citizens.',
    description: 'Ethereum-based virtual world where players buy, build, and monetize land as NFTs.',
    url: 'https://decentraland.org',
    thumbnail: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&q=80',
    biome: 'crystal-spires',
    tags: ['Web3', 'VR', 'Free', 'NFT', 'Metaverse'],
    coordinates: [680, 1200],
    visitors: 56_000,
    rating: 3.5,
  },
  {
    id: 'horizon-worlds',
    name: 'Meta Horizon Worlds',
    lore: 'The Arcane Lens — a realm fashioned by the All-Seeing Eye, where reality bends to the wearer of the sacred Visor.',
    description: 'Meta\'s flagship VR social platform for Quest headsets and browser.',
    url: 'https://www.meta.com/horizon-worlds/',
    thumbnail: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=400&q=80',
    biome: 'crystal-spires',
    tags: ['VR', 'Social', 'Free', 'Mobile', 'Meta'],
    coordinates: [540, 800],
    visitors: 300_000,
    rating: 3.2,
  },
  // ── Shadow Realms (indie / experimental) ──────────────────────────────
  {
    id: 'neos-vr',
    name: 'Resonite',
    lore: 'The Resonance Labyrinth — an ever-shifting realm where the most arcane artificers gather to forge impossible things.',
    description: 'Highly technical, developer-focused VR world with in-world programming and rich modding.',
    url: 'https://resonite.com',
    thumbnail: 'https://images.unsplash.com/photo-1608501078713-8e445a709b39?w=400&q=80',
    biome: 'shadow-realms',
    tags: ['VR', 'Technical', 'Indie', 'Paid'],
    coordinates: [2600, 1500],
    visitors: 45_000,
    rating: 4.6,
  },
  {
    id: 'high-fidelity',
    name: 'Vircadia',
    lore: 'The Wandering Sanctum — a forgotten archive built by heretic architects, preserved by those who seek truth over spectacle.',
    description: 'Open-source metaverse platform forked from High Fidelity, self-hostable.',
    url: 'https://vircadia.com',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80',
    biome: 'shadow-realms',
    tags: ['Open-Source', 'Free', 'VR', 'Self-Hosted'],
    coordinates: [2750, 1300],
    visitors: 8_000,
    rating: 3.8,
  },
  // ── Floating Isles (browser-based) ────────────────────────────────────
  {
    id: 'mozilla-hubs',
    name: 'Mozilla Hubs',
    lore: 'The Cloudspire of the Open Web — no artifact of power is required, only a scrying-glass browser, to pass through this portal.',
    description: 'Browser-based VR social spaces by Mozilla. No download required.',
    url: 'https://hubs.mozilla.com',
    thumbnail: 'https://images.unsplash.com/photo-1553481187-be93c21490a9?w=400&q=80',
    biome: 'floating-isles',
    tags: ['Browser', 'Free', 'VR', 'Open-Source'],
    coordinates: [1700, 1650],
    visitors: 120_000,
    rating: 4.0,
  },
  {
    id: 'gather-town',
    name: 'Gather.town',
    lore: 'The Pixel Sanctum — a two-dimensional realm of pixels and proximity, where whispers travel only to those who stand nearby.',
    description: 'Pixel-art virtual office / event space with proximity-based video chat.',
    url: 'https://www.gather.town',
    thumbnail: 'https://images.unsplash.com/photo-1577412647305-991150c7d163?w=400&q=80',
    biome: 'floating-isles',
    tags: ['Browser', 'Social', 'Work', 'Free'],
    coordinates: [1550, 1780],
    visitors: 4_000_000,
    rating: 4.2,
  },
  // ── Void Nexus (abstract / AI) ─────────────────────────────────────────
  {
    id: 'ai-town',
    name: 'AI Town',
    lore: 'The Living Grimoire — a world populated by bound spirits of pure thought, endlessly dreaming their own destinies.',
    description: 'Experimental open-source AI simulation where autonomous agents live, talk, and remember.',
    url: 'https://github.com/a16z-infra/ai-town',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&q=80',
    biome: 'void-nexus',
    tags: ['AI', 'Open-Source', 'Experimental', 'Free'],
    coordinates: [400, 1500],
    visitors: 22_000,
    rating: 4.4,
  },
  // ── Dragon Peaks (competitive / gaming) ────────────────────────────────
  {
    id: 'gta-online',
    name: 'GTA Online',
    lore: 'The Crimson Badlands — a lawless frontier where fortune and infamy are separated only by the swiftness of a blade.',
    description: 'Rockstar\'s ever-expanding multiplayer world within Grand Theft Auto V.',
    url: 'https://www.rockstargames.com/gta-online',
    thumbnail: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&q=80',
    biome: 'dragon-peaks',
    tags: ['Gaming', 'Multiplayer', 'Paid', 'Action'],
    coordinates: [2800, 600],
    visitors: 100_000_000,
    rating: 4.0,
  },
];
