// Virtual Worlds – curated seed data for the map
// Coordinates are in [lat (y), lng (x)] for Leaflet CRS.Simple
// Map is 8000x5000, so coordinates should be within that range
import type { WorldMarker } from './worldTypes';

export const SEED_WORLDS: WorldMarker[] = [
  // ═══ ENCHANTED FORESTS – northwest (social / roleplay) ═══════════════

  {
    id: 'second-life',
    name: 'Second Life',
    lore: 'Where souls seek another existence beyond mortal flesh — the oldest of the Great Kingdoms, built upon millions of whispered wishes.',
    description: 'The original metaverse. A vast 3D social world where users build, trade, and live alternate lives since 2003.',
    url: 'https://secondlife.com',
    thumbnail: 'https://images.unsplash.com/photo-1518050346340-aa2ec3bb424b?w=400&q=80',
    biome: 'enchanted-forest',
    tags: ['Social', 'Roleplay', 'Free', 'Desktop'],
    coordinates: [1500, 2600],
    visitors: 824_000,
    rating: 4.1,
  },
  {
    id: 'imvu',
    name: 'IMVU',
    lore: 'The Glittering Bazaar — a realm where identity is forged in the flames of fashion, and every avatar is a masterwork.',
    description: 'Social avatar platform with 3D chat rooms, fashion, and a thriving creator economy.',
    url: 'https://www.imvu.com',
    thumbnail: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=400&q=80',
    biome: 'enchanted-forest',
    tags: ['Social', 'Free', 'Mobile', 'Fashion'],
    coordinates: [1250, 3050],
    visitors: 7_000_000,
    rating: 3.9,
  },
  {
    id: 'habbo',
    name: 'Habbo Hotel',
    lore: 'The Pixelated Inn — a legendary watering hole at the edge of the Enchanted Forest, where every room tells a story.',
    description: 'Classic pixel-art social MMO hotel. Build rooms, make friends, play games. A web icon since 2000.',
    url: 'https://www.habbo.com',
    thumbnail: 'https://images.unsplash.com/photo-1562280963-8a5475740a10?w=400&q=80',
    biome: 'enchanted-forest',
    tags: ['Browser', 'Social', 'Free', 'Classic'],
    coordinates: [1700, 2400],
    visitors: 2_500_000,
    rating: 3.7,
  },

  // ═══ MOUNTAIN FORGES – northeast (creative sandboxes) ══════════════

  {
    id: 'minecraft',
    name: 'Minecraft',
    lore: 'The Forge Eternal — where from raw stone and timber, entire civilisations rise at the will of the maker.',
    description: 'The legendary block-building sandbox beloved by hundreds of millions across the globe.',
    url: 'https://minecraft.net',
    thumbnail: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400&q=80',
    biome: 'mountain-forge',
    tags: ['Sandbox', 'Creative', 'Multiplayer', 'Paid'],
    coordinates: [1400, 5200],
    visitors: 175_000_000,
    rating: 4.9,
  },
  {
    id: 'roblox',
    name: 'Roblox',
    lore: 'The Infinite Spire of Games — a tower that contains ten thousand worlds, each built by young artificers who dare to dream.',
    description: 'Massively popular platform letting users create and play in millions of user-made games.',
    url: 'https://roblox.com',
    thumbnail: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80',
    biome: 'mountain-forge',
    tags: ['Sandbox', 'Free', 'Multiplayer', 'Mobile'],
    coordinates: [1700, 5600],
    visitors: 214_000_000,
    rating: 4.3,
  },
  {
    id: 'terraria',
    name: 'Terraria',
    lore: 'The Caverns of Infinite Depth — where every block hides a secret and every biome holds a boss.',
    description: '2D sandbox adventure with deep crafting, exploration, and combat. A genre-defining indie hit.',
    url: 'https://terraria.org',
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&q=80',
    biome: 'mountain-forge',
    tags: ['Sandbox', 'Adventure', 'Multiplayer', 'Paid'],
    coordinates: [1100, 5850],
    visitors: 58_000_000,
    rating: 4.8,
  },
  {
    id: 'core',
    name: 'Core by Manticore',
    lore: 'The Anvil of Instant Creation — where games spring to life with a thought and are shared with the world in a heartbeat.',
    description: 'Unreal-powered game creation platform. Build, share, and play multiplayer games for free.',
    url: 'https://www.coregames.com',
    thumbnail: 'https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=400&q=80',
    biome: 'mountain-forge',
    tags: ['Sandbox', 'Free', 'Multiplayer', 'Game Dev'],
    coordinates: [1900, 5400],
    visitors: 3_000_000,
    rating: 3.6,
  },

  // ═══ CRYSTAL SPIRES – west coast (VR / metaverse) ═══════════════════

  {
    id: 'vrchat',
    name: 'VRChat',
    lore: 'The Grand Agora of Avatars — a realm where any form may be worn and any world can be entered through crystalline gates.',
    description: 'Social VR platform with user-generated worlds and expressive avatar customization.',
    url: 'https://vrchat.com',
    thumbnail: 'https://images.unsplash.com/photo-1626379616243-44dc20e77de0?w=400&q=80',
    biome: 'crystal-spires',
    tags: ['VR', 'Social', 'Free', 'Multiplayer'],
    coordinates: [2200, 1400],
    visitors: 5_200_000,
    rating: 4.7,
  },
  {
    id: 'decentraland',
    name: 'Decentraland',
    lore: 'The Crystal Sovereignty — an autonomous realm where land is forever enshrined in the Blockchain Codex, owned by its citizens.',
    description: 'Ethereum-based virtual world where players buy, build, and monetize land as NFTs.',
    url: 'https://decentraland.org',
    thumbnail: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&q=80',
    biome: 'crystal-spires',
    tags: ['Web3', 'VR', 'Free', 'NFT', 'Metaverse'],
    coordinates: [2700, 1600],
    visitors: 56_000,
    rating: 3.5,
  },
  {
    id: 'horizon-worlds',
    name: 'Meta Horizon Worlds',
    lore: 'The Arcane Lens — a realm fashioned by the All-Seeing Eye, where reality bends to the wearer of the sacred Visor.',
    description: "Meta's flagship VR social platform for Quest headsets and browser.",
    url: 'https://www.meta.com/horizon-worlds/',
    thumbnail: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=400&q=80',
    biome: 'crystal-spires',
    tags: ['VR', 'Social', 'Free', 'Mobile', 'Meta'],
    coordinates: [2500, 1200],
    visitors: 300_000,
    rating: 3.2,
  },
  {
    id: 'rec-room',
    name: 'Rec Room',
    lore: 'The Cheerful Citadel — a bright fortress where every door leads to a new game and laughter echoes through crystalline halls.',
    description: 'Free cross-platform VR social game with user-created rooms and mini-games.',
    url: 'https://recroom.com',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80',
    biome: 'crystal-spires',
    tags: ['VR', 'Free', 'Multiplayer', 'Cross-Platform'],
    coordinates: [3000, 1500],
    visitors: 4_000_000,
    rating: 4.1,
  },

  // ═══ SHADOW REALMS – far east (indie / experimental) ════════════════

  {
    id: 'resonite',
    name: 'Resonite',
    lore: 'The Resonance Labyrinth — an ever-shifting realm where the most arcane artificers gather to forge impossible things.',
    description: 'Highly technical, developer-focused VR world with in-world programming and rich modding.',
    url: 'https://resonite.com',
    thumbnail: 'https://images.unsplash.com/photo-1608501078713-8e445a709b39?w=400&q=80',
    biome: 'shadow-realms',
    tags: ['VR', 'Technical', 'Indie', 'Paid'],
    coordinates: [3000, 6500],
    visitors: 45_000,
    rating: 4.6,
  },
  {
    id: 'vircadia',
    name: 'Vircadia',
    lore: 'The Wandering Sanctum — a forgotten archive built by heretic architects, preserved by those who seek truth over spectacle.',
    description: 'Open-source metaverse platform forked from High Fidelity, self-hostable.',
    url: 'https://vircadia.com',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80',
    biome: 'shadow-realms',
    tags: ['Open-Source', 'Free', 'VR', 'Self-Hosted'],
    coordinates: [3300, 6800],
    visitors: 8_000,
    rating: 3.8,
  },
  {
    id: 'webaverse',
    name: 'Webaverse',
    lore: 'The Open Scroll — an experimental grimoire where the very code is the world, and every adventurer is also its author.',
    description: 'Open-source web-native metaverse engine. Build VR/AR worlds with web standards.',
    url: 'https://webaverse.com',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&q=80',
    biome: 'shadow-realms',
    tags: ['Open-Source', 'Web3', 'Indie', 'Free'],
    coordinates: [2800, 6300],
    visitors: 12_000,
    rating: 3.4,
  },

  // ═══ FLOATING ISLES – south (browser-based) ═════════════════════════

  {
    id: 'mozilla-hubs',
    name: 'Mozilla Hubs',
    lore: 'The Cloudspire of the Open Web — no artifact of power is required, only a scrying-glass browser to pass through this portal.',
    description: 'Browser-based VR social spaces by Mozilla. No download required.',
    url: 'https://hubs.mozilla.com',
    thumbnail: 'https://images.unsplash.com/photo-1553481187-be93c21490a9?w=400&q=80',
    biome: 'floating-isles',
    tags: ['Browser', 'Free', 'VR', 'Open-Source'],
    coordinates: [4100, 3800],
    visitors: 120_000,
    rating: 4.0,
  },
  {
    id: 'gather-town',
    name: 'Gather.town',
    lore: 'The Pixel Sanctum — a two-dimensional realm of pixels and proximity, where whispers travel only to those who stand nearby.',
    description: 'Pixel-art virtual office / event space with proximity-based video chat.',
    url: 'https://www.gather.town',
    thumbnail: 'https://images.unsplash.com/photo-1577412647305-991150c7d163?w=400&q=80',
    biome: 'floating-isles',
    tags: ['Browser', 'Social', 'Work', 'Free'],
    coordinates: [4300, 4200],
    visitors: 4_000_000,
    rating: 4.2,
  },
  {
    id: 'spatial',
    name: 'Spatial',
    lore: 'The Hovering Gallery — an isle of art and commerce suspended in the sky, where creators exhibit their finest works.',
    description: 'Browser 3D social platform for events, NFT galleries, and virtual spaces. No download.',
    url: 'https://spatial.io',
    thumbnail: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80',
    biome: 'floating-isles',
    tags: ['Browser', 'NFT', 'Free', 'Social'],
    coordinates: [3900, 4500],
    visitors: 800_000,
    rating: 3.8,
  },

  // ═══ VOID NEXUS – far west (abstract / AI) ══════════════════════════

  {
    id: 'ai-town',
    name: 'AI Town',
    lore: 'The Living Grimoire — a world populated by bound spirits of pure thought, endlessly dreaming their own destinies.',
    description: 'Experimental open-source AI simulation where autonomous agents live, talk, and remember.',
    url: 'https://github.com/a16z-infra/ai-town',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&q=80',
    biome: 'void-nexus',
    tags: ['AI', 'Open-Source', 'Experimental', 'Free'],
    coordinates: [3200, 700],
    visitors: 22_000,
    rating: 4.4,
  },
  {
    id: 'worldcoin-world',
    name: 'World App',
    lore: 'The Eye of Truth — a nexus where mortal identity meets digital omniscience, and proof-of-personhood is the only key.',
    description: 'Worldcoin\'s identity-verified digital world and financial network.',
    url: 'https://worldcoin.org',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&q=80',
    biome: 'void-nexus',
    tags: ['AI', 'Web3', 'Identity', 'Free'],
    coordinates: [3400, 900],
    visitors: 10_000_000,
    rating: 3.3,
  },

  // ═══ DRAGON PEAKS – far northeast (competitive / gaming) ════════════

  {
    id: 'gta-online',
    name: 'GTA Online',
    lore: 'The Crimson Badlands — a lawless frontier where fortune and infamy are separated only by the swiftness of a blade.',
    description: "Rockstar's ever-expanding multiplayer world within Grand Theft Auto V.",
    url: 'https://www.rockstargames.com/gta-online',
    thumbnail: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&q=80',
    biome: 'dragon-peaks',
    tags: ['Gaming', 'Multiplayer', 'Paid', 'Action'],
    coordinates: [1100, 7000],
    visitors: 100_000_000,
    rating: 4.0,
  },
  {
    id: 'fortnite',
    name: 'Fortnite',
    lore: 'The Storm Arena — an ever-shifting battleground where a hundred warriors descend and only one stands victorious.',
    description: 'Battle royale turned cultural phenomenon with concerts, events, and creative mode.',
    url: 'https://www.fortnite.com',
    thumbnail: 'https://images.unsplash.com/photo-1589241062272-c0a000072dfa?w=400&q=80',
    biome: 'dragon-peaks',
    tags: ['Gaming', 'Free', 'Multiplayer', 'Battle Royale'],
    coordinates: [1300, 6700],
    visitors: 350_000_000,
    rating: 4.4,
  },
  {
    id: 'eve-online',
    name: 'EVE Online',
    lore: 'The Void Between Stars — a universe of intrigue, war, and commerce where player empires span galaxies.',
    description: 'Massive space MMO known for its player-driven economy and epic fleet battles.',
    url: 'https://www.eveonline.com',
    thumbnail: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&q=80',
    biome: 'dragon-peaks',
    tags: ['MMO', 'Sci-Fi', 'Paid', 'PvP'],
    coordinates: [900, 6800],
    visitors: 500_000,
    rating: 4.5,
  },

  // ═══ SUNKEN DEPTHS – center (sci-fi / underwater) ═══════════════════

  {
    id: 'no-mans-sky',
    name: "No Man's Sky",
    lore: 'The Infinite Abyss of Stars — an ocean of 18 quintillion worlds, each waiting to be the first footprint upon its shore.',
    description: 'Procedurally generated space exploration with 18 quintillion planets. A redemption story.',
    url: 'https://www.nomanssky.com',
    thumbnail: 'https://images.unsplash.com/photo-1462332420958-a05d1e002413?w=400&q=80',
    biome: 'sunken-depths',
    tags: ['Exploration', 'Sci-Fi', 'Multiplayer', 'Paid'],
    coordinates: [2700, 3800],
    visitors: 40_000_000,
    rating: 4.3,
  },
  {
    id: 'star-citizen',
    name: 'Star Citizen',
    lore: 'The Unfinished Colossus — the most ambitious vessel ever conceived, still being forged in the docks of ambition.',
    description: 'Massively ambitious space MMO with unprecedented fidelity. Still in alpha with a dedicated community.',
    url: 'https://robertsspaceindustries.com',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&q=80',
    biome: 'sunken-depths',
    tags: ['MMO', 'Sci-Fi', 'Paid', 'Alpha'],
    coordinates: [2900, 4100],
    visitors: 4_800_000,
    rating: 3.6,
  },
];
